import "quasar/dist/quasar.css"
import "@quasar/extras/material-icons/material-icons.css"
import "@quasar/extras/fontawesome-v5/fontawesome-v5.css"

import Quasar, {
    Notify,
    QSplitter,
    QMenu,
    QAvatar,
    ClosePopup,
    QTree,
    QBadge,
    QBtn,
    QSelect,
    QCard,
    QCardSection,
    QCardActions,
    QCheckbox,
    QDialog,
    QFile,
    QFooter,
    QForm,
    QHeader,
    QIcon,
    QInnerLoading,
    QInput,
    QItem,
    QItemLabel,
    QItemSection,
    QLayout,
    QLinearProgress,
    QList,
    QPage,
    QPageContainer,
    QScrollArea,
    QSeparator,
    QSpace,
    QSpinner,
    QToggle,
    QToolbar,
    QDrawer,
    QToolbarTitle,
} from "quasar"

export default [Quasar, {
    components: {
        QBadge,
        QDrawer,
         QMenu,
        QBtn,
        QAvatar,
        QSplitter,
        QSelect,
        QTree,
        QCard,
        QCardSection,
        QCardActions,
        QCheckbox,
        QDialog,
        QFile,
        QFooter,
        QForm,
        QHeader,
        QIcon,
        QInnerLoading,
        QInput,
        QItem,
        QItemLabel,
        QItemSection,
        QLayout,
        QLinearProgress,
        QList,
        QPage,
        QPageContainer,
        QScrollArea,
        QSeparator,
        QSpace,
        QSpinner,
        QToggle,
        QToolbar,
        QToolbarTitle,
    },
    plugins: {
        Notify,
        ClosePopup
    }
}]
